import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// @ts-ignore - this file is generated by `remix vite:build`
import * as build from "../build/server/index.js";

export const onRequest = createPagesFunctionHandler({
    build,
    getLoadContext: (context) => ({
        cloudflare: {
            env: context.env,
            cf: context.request.cf as any,
            ctx: {
                waitUntil: context.waitUntil,
                passThroughOnException: context.passThroughOnException,
            } as any,
            caches,
        },
    }),
});
